# This file generates the GitHub Actions matrix
# For simple single keyboard builds, remove everything but your keyboard
---
include:
  - board: nice_nano
    shield: souffle_v3_sweep_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    shield: souffle_v3_sweep_right