# This file generates the GitHub Actions matrix
# For simple single keyboard builds, remove everything but your keyboard
---
include:
  - board: nice_nano
    shield: souffle_v3_sweep_left
    snippet: zmk-usb-logging
  - board: nice_nano
    shield: souffle_v3_sweep_right
    snippet: zmk-usb-logging